services:
  proxy:
    image: nginxproxy/nginx-proxy
    container_name: rally-nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: rally-web
    environment:
      VIRTUAL_HOST: rally-logistique.cloud,www.rally-logistique.cloud
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: rally-proxy
