services:
  proxy:
    image: nginxproxy/nginx-proxy
    container_name: rally-nginx-proxy
    labels:
      - "com.github.nginx-proxy.nginx=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost_d:/etc/nginx/vhost.d
      - html_acme:/usr/share/nginx/html
    networks:
      - proxy
    restart: unless-stopped

  acme:
    image: nginxproxy/acme-companion
    container_name: rally-acme
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
    environment:
      DEFAULT_EMAIL: "${LETSENCRYPT_EMAIL}"
      NGINX_PROXY_CONTAINER: rally-nginx-proxy
    networks:
      - proxy
    depends_on:
      - proxy
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: rally-web
    environment:
      VIRTUAL_HOST: rally-logistique.cloud,www.rally-logistique.cloud
      LETSENCRYPT_HOST: rally-logistique.cloud,www.rally-logistique.cloud
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - proxy
    restart: unless-stopped

volumes:
  certs:
  vhost_d:
  html_acme:

networks:
  proxy:
    name: rally-proxy
